# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7550d92ace369c843258cea3b6a5e1a03d4f718da919880f02a33db0684041c861934e2d2bfbda1e335b39de0ab8244d3d5bba9b5c60e7689938890f07227cab

test:
  secret_key_base: 67a9d10dd4b608ba81587b8a5b941cd65699bb626be4fa1b37554e1f22352ba2ed29af10b9627a5cc0e43009b7fa683888afa3950804290bc2d04028a9e9691d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
